config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }
  root 'home#index'
  resources :buffets, only: %i[index show new create edit update]

  resources :events, only: %i[show new create edit update destroy] do
    resources :event_costs, only: %i[new create edit update]
    resources :orders, only: %i[new create]
  end

  resources :orders, only: %i[show index] do
    resources :proposals, only: %i[show new create] do
      patch :accept, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index show] do
          resources :orders, only: %i[create]
        end
      end
    end
  end

  match '*unmatched', to: 'errors#error404', via: :all
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :buffet
  has_many :event_costs

  validates :name, :description, :min_people, :max_people, :duration, :menu, :buffet_id, presence: true
  validate :min_people_positive, :max_people_positive, :duration_positive

  private

  def min_people_positive
    return if min_people.to_i.positive?

    errors.add(:min_people, 'deve ser positivo')
  end

  def max_people_positive
    return if max_people.to_i.positive?

    errors.add(:max_people, 'deve ser positivo')
  end

  def duration_positive
    return if duration.to_i.positive?

    errors.add(:duration, 'deve ser positivo')
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::ApiController
  def index
    buffet_id = params[:buffet_id]
    begin
      Buffet.find(buffet_id)
      events = Event.where(buffet_id:)
      render status: 200, json: events.as_json(only: %i[id name description], include: include_on_events)
    rescue ActiveRecord::RecordNotFound
      render status: 404, json: { error: { message: 'Buffet não encontrado. Verifique o ID' } }
    end
  end

  def show
    event = Event.find(params[:id])
    render status: 200, json: event.to_json(except: %i[buffet_id created_at updated_at])
  end

  private

  def include_on_events
    { buffet: { only: %i[id brand_name] } }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_owner!, except: %i[show]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :redirect_to_buffet, only: %i[show edit update destroy]

  def show
    @buffet = @event.buffet
    @event_costs = @event.event_costs
  end

  def new
    @buffet = current_owner.buffet
    @event = Event.new
  end

  def create
    buffet = current_owner.buffet
    @event = Event.new(event_params)
    buffet.events << @event

    if @event.save
      redirect_to @event, notice: 'Evento criado com sucesso!'
    else
      @event_errors = @event.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Evento atualizado com sucesso!'
    else
      @event_errors = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    buffet = @event.buffet
    event_name = @event.name
    @event.destroy
    redirect_to buffet, notice: "#{event_name} excluído(a) com sucesso"
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :min_people, :max_people, :duration, :menu, :alcoholic_beverages,
                                  :decoration, :parking, :parking_valet, :customer_space)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def redirect_to_buffet
    return unless owner_signed_in?

    owner_buffet = current_owner.buffet
    redirect_to owner_buffet if @event.buffet != owner_buffet
  end
end

app/views/events/_form.html.erb
<%= form_with model: @event, id: 'form-event' do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :min_people %>
    <%= f.number_field :min_people %>
  </div>

  <div>
    <%= f.label :max_people %>
    <%= f.number_field :max_people %>
  </div>

  <div>
    <%= f.label :duration %>
    <%= f.number_field :duration %>
  </div>

  <div>
    <%= f.label :menu %>
    <%= f.text_field :menu %>
  </div>

  <div>
    <%= f.label :alcoholic_beverages %>
    <%= f.check_box :alcoholic_beverages %>
  </div>

  <div>
    <%= f.label :decoration %>
    <%= f.check_box :decoration %>
  </div>

  <div>
    <%= f.label :parking %>
    <%= f.check_box :parking %>
  </div>

  <div>
    <%= f.label :parking_valet %>
    <%= f.check_box :parking_valet %>
  </div>

  <div>
    <%= f.label :customer_space %>
    <%= f.check_box :customer_space %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editar <%= @event.name %></h1>

<div>
  <p><%= link_to 'Voltar para Evento', @event %></p>
</div>

<% if @event_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>
    
    <% @event_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    
  </ul>
<% end %>

<div>
  <%= render partial: 'form' %>
</div>

app/views/events/new.html.erb
<h1>Cadastrar Evento</h1>

<div>
  <p><%= link_to 'Voltar para Buffet', @buffet %></p>
</div>

<% if @event_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>
    
    <% @event_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    
  </ul>
<% end %>

<div>
  <%= render partial: 'form' %>
</div>

app/views/events/show.html.erb
<h1>Buffet <%= @event.buffet.brand_name %></h1>
<h2><%= @event.name %></h2>

<div>
  <p><%= link_to 'Voltar para Buffet', @buffet %></p>
</div>

<% if owner_signed_in? %>
  <div>
    <%= link_to 'Editar Evento', edit_event_path(@event) %> | 
    <%= link_to 'Adicionar Custos do Evento', new_event_event_cost_path(@event) %>
    <%= button_to 'Excluir Evento', @event, method: :delete, onclick: "return confirm('Você tem certeza que deseja excluir o evento?');" %>
  </div>
<% end %>

<dl>
  <div>
    <dt><%= I18n.t 'activerecord.attributes.event.description' %>:</dt>
    <dd><%= @event.description %></dd>
  </div>
  
  <div>
    <dt><%= I18n.t 'activerecord.attributes.event.min_people' %>:</dt>
    <dd><%= @event.min_people %></dd>
  </div>
  
  <div>
    <dt><%= I18n.t 'activerecord.attributes.event.max_people' %>:</dt>
    <dd><%= @event.max_people %></dd>
  </div>
  
  <div>
    <dt><%= I18n.t 'activerecord.attributes.event.duration' %></dt>
    <dd><%= @event.duration %> min</dd>
  </div>
  
  <div>
    <dt><%= I18n.t 'activerecord.attributes.event.menu' %>:</dt>
    <dd><%= @event.menu %></dd>
  </div>

  <div>
    <dt>Serviços:</dt>
    <dd>
      <ul>
        <% if @event.alcoholic_beverages %>
          <li><%= I18n.t 'activerecord.attributes.event.alcoholic_beverages' %></li>
        <% end %>

        <% if @event.decoration %>
          <li><%= I18n.t 'activerecord.attributes.event.decoration' %></li>
        <% end %>

        <% if @event.parking %>
          <li><%= I18n.t 'activerecord.attributes.event.parking' %></li>
        <% end %>

        <% if @event.parking_valet %>
          <li><%= I18n.t 'activerecord.attributes.event.parking_valet' %></li>
        <% end %>

        <% if @event.customer_space %>
          <li><%= I18n.t 'activerecord.attributes.event.customer_space' %></li>
        <% end %>
      </ul>
    </dd>
  </div>
</dl>

<h2>Valores</h2>
<section id='event-cost'>
  <% if @event_costs.present? %>
    <% @event_costs.each do |event_cost| %>
      <div id=<%= event_cost.description.downcase.gsub(' ', '-') %> >
        <div>
          <p>
            <%= event_cost.description %>
            <% if owner_signed_in? %>
              | <%= link_to 'Editar', edit_event_event_cost_path(@event) %>
            <% end %>
          </p>
        </div>

        <dl>
          <div>
            <dt><%= 'Valor inicial:' %></dt>
            <dd><%= event_cost.minimum %></dd>
          </div>

          <div>
            <dt><%= 'Preço adicional:' %></dt>
            <dd><%= event_cost.additional_per_person %>/pessoa</dd>
          </div>

          <div>
            <dt><%= 'Hora extra:' %></dt>
            <dd><%= event_cost.overtime %>/hora</dd>
          </div>
        </dl>
      </div>
    <% end %>
  <% else %>
    <p>Nenhum valor cadastrado</p>
  <% end %>
</section>

<% if customer_signed_in? %>
  <h2><%= link_to 'Contratar serviço', new_event_order_path(@event) %></h2>
<% end %>