config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }
  root 'home#index'
  resources :buffets, only: %i[index show new create edit update]

  resources :events, only: %i[show new create edit update destroy] do
    resources :event_costs, only: %i[new create edit update]
    resources :orders, only: %i[new create]
  end

  resources :orders, only: %i[show index] do
    resources :proposals, only: %i[show new create] do
      patch :accept, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index show] do
          resources :orders, only: %i[create]
        end
      end
    end
  end

  match '*unmatched', to: 'errors#error404', via: :all
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buffet
  belongs_to :customer
  belongs_to :event

  validates :event_date, :people, :details, :address, :buffet_id, :customer_id, :event_id, presence: true
  validate :event_date_furute, :people_positive

  before_validation :generate_code, on: :create

  enum status: { pending: 0, approved: 5, canceled: 9 }

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  private

  def event_date_furute
    return if event_date && event_date > Date.today

    errors.add(:event_date, 'deve ser futura')
  end

  def people_positive
    return if people&.positive?

    errors.add(:people, 'deve ser positivo')
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApiController
  rescue_from ActionController::ParameterMissing, with: :return_412

  def create
    @event = Event.find(params[:event_id])
    @order = Order.new(order_params)
    @order.event = @event
    if order_valid_api?
      advance_price = "R$ #{format('%.2f', event_cost_calculate / 100.0)}"
      render status: 201, json: { advance_price: }
    else
      render status: 412, json: { errors: @error_messages }
    end
  end

  private

  def event_cost_calculate
    event_cost.minimum + event_cost.additional_per_person * (@order.people - @event.min_people)
  end

  def event_cost
    event_cost_select || @event.event_costs.first
  end

  def event_cost_select
    if @order.event_date.on_weekday?
      @event.event_costs.find { |event| event.description == 'Dias de semana' }
    else
      @event.event_costs.find { |event| event.description == 'Fim de semana' }
    end
  end

  def order_params
    params.require(:order).permit(:event_date, :people)
  end

  def return_412
    render status: 412, json: { error: 'Order não pode ficar em branco' }
  end

  def order_valid_api?
    present_parameters? && available_date?
  end

  def present_parameters?
    return true if order_params[:event_date] && order_params[:people]

    @error_messages = ['Data do evento não pode ficar em branco', 'Quantidade de pessoas não pode ficar em branco']
    false
  end

  def available_date?
    if Order.find_by(event_date: order_params[:event_date])
      @error_messages = 'Buffet indisponível na data escolhida'
      false
    else
      true
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!, only: %i[create]

  def index
    if owner_signed_in?
      @buffet = current_owner.buffet
      orders = Order.where(buffet: @buffet)
      @pending_orders = orders.select(&:pending?)
      @approved_orders = orders.select(&:approved?)
      @canceled_orders = orders.select(&:canceled?)
    else
      @orders = Order.where(customer: current_customer)
      @proposal_orders = Proposal.where(customer: current_customer).select { |order| order.status == 'sent' }
    end
  end

  def show
    order_id = params[:id].to_i
    @order = Order.find(order_id)
    redirect_to root_path unless current_owner == @order.buffet.owner || current_customer == @order.customer

    @conflicting_orders = Order.where(event_date: @order.event_date).reject { |order| order.id == order_id }
  end

  def new
    @event = Event.find(params[:event_id])
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @event = Event.find(params[:event_id])
    @order.event = @event
    @order.buffet = @event.buffet
    @order.customer = current_customer

    if @order.save
      redirect_to @order, notice: 'Pedido realizado com sucesso. Aguardar aprovação do Buffet'
    else
      @order_errors = @order.errors.full_messages
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:event_date, :people, :details, :address)
  end
end

app/views/orders/index.html.erb
<% if customer_signed_in? %>
  <h1 id=customer-orders>Meus Pedidos</h1>
<% elsif owner_signed_in? %>
  <h1 id=buffet-orders>Pedidos do <%= @buffet.brand_name %></h1>
<% end %>

<% if customer_signed_in? %>
  <h2>Aguardando Confirmação:</h2>
    <% @proposal_orders.each do |proposal_order| %>
      <% next if proposal_order.proposal_expired? %>
      <%= I18n.l proposal_order.order.event_date %> - <%= proposal_order.order.code %>: Confirmar até <%= l proposal_order.validate_date %>
      <%= link_to 'Ver proposta', order_proposal_path(proposal_order.order, proposal_order) %>
    <% end %>
<% end %>

<% if customer_signed_in? %>
  <section>

    <% if @orders.present? %>
      <% @orders.each do |order| %>

        <div>
          <%= link_to order do %>
            <%= I18n.l order.event_date %> - <%= order.code %>
          <% end %>
        </div>

      <% end %>

    <% else %>
      <p>Nenhum pedido cadastrado</p>
    <% end %>

  </section>

<% elsif owner_signed_in? %>
  <section>
    <p>Aguardando avaliação:</p>

    <% if @pending_orders.present? %>
      <% @pending_orders.each do |order| %>

        <ul>
          <%= link_to order do %>
            <li><%= I18n.l order.event_date %> - <%= order.code %></li>
          <% end %>
        </ul>

      <% end %>
    <% else %>
      <p>Nenhum evento pendente.</p>

    <% end %>
  </section>

  <section>
    <p>Aprovados:</p>
    
    <% if @approved_orders.present? %>
      <% @approved_orders.each do |order| %>

        <ul>
          <%= link_to order do %>
            <li><%= I18n.l order.event_date %> - <%= order.code %></li>
          <% end %>
        </ul>

      <% end %>
    <% else %>
      <p>Nenhum evento aprovado.</p>

    <% end %>
  </section>

  <section>
    <p>Cancelados:</p>
    
    <% if @canceled_orders.present? %>
      <% @canceled_orders.each do |order| %>

        <ul>
          <%= link_to order do %>
            <li><%= I18n.l order.event_date %> - <%= order.code %></li>
          <% end %>
        </ul>

      <% end %>
    <% else %>
      <p>Nenhum evento cancelado.</p>

    <% end %>
  </section>
<% end %>

app/views/orders/new.html.erb
<h1>Contratar <%= @event.name %></h1>

<div>
  <p><%= link_to 'Voltar para Evento', @event %></p>
</div>

<% if @order_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>

    <% @order_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    
  </ul>

<% end %>

<%= form_with model: [@event, @order] do |f| %>
  <div>
    <%= f.label :event_date %>
    <%= f.date_field :event_date %>
  </div>

  <div>
    <%= f.label :people %>
    <%= f.number_field :people %>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <% if @event.customer_space %>
    <div>
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
  <% end %>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h1><%= I18n.l(@order.event_date) %> - <%= @order.code %></h1>

<div>
  <p><%= link_to 'Voltar para Pedidos', orders_path %></p>
</div>

<%# Validação para somente o Proprietáiro ver esse aviso %>
<ul>
  <% @conflicting_orders.each do |conflicting_order| %>
    <li>AVISO: Evento <%= l conflicting_order.event_date %> - <%= conflicting_order.code %> no MESMO DIA!!!</li>
  <% end %>
</ul>

<p><%= @order.buffet.brand_name %></p>

<dl>
  <div>
    <dt>Evento:</dt>
    <dd><%= @order.event.name %></dd>
  </div>

  <div>
    <dt>Status:</dt>
    <dd><%= t @order.status %></dd>
  </div>

  <div>
    <dt>Detalhes da festa:</dt>
    <dd><%= @order.details %></dd>
  </div>

  <div>
    <dt>Local da festa:</dt>
    <dd><%= @order.address %></dd>
  </div>

  <div>
    <dt>Número de pessoas:</dt>
    <dd><%= @order.people %></dd>
  </div>
</dl>

<% if owner_signed_in? %>
  <%= link_to 'Aprovar pedido', new_order_proposal_path(@order) %>
<% end %>