config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }
  root 'home#index'
  resources :buffets, only: %i[index show new create edit update]

  resources :events, only: %i[show new create edit update destroy] do
    resources :event_costs, only: %i[new create edit update]
    resources :orders, only: %i[new create]
  end

  resources :orders, only: %i[show index] do
    resources :proposals, only: %i[show new create] do
      patch :accept, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: %i[index show] do
        resources :events, only: %i[index show] do
          resources :orders, only: %i[create]
        end
      end
    end
  end

  match '*unmatched', to: 'errors#error404', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Td12FindBuffets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Buffets</h1>
      <% end %>
      <nav>
        <div id=search>
          <%= form_with url: buffets_path, method: :get do |f| %>

            <%= f.label :query, 'Buscar Buffet' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>

          <% end %>
        </div>
        <div id=owner-login>

          <% if owner_signed_in? %>
            <%= current_owner.description %> | 
            <%= link_to 'Pedidos', orders_path %>
            <%= button_to 'Sair', destroy_owner_session_path, method: :delete %>

          <% elsif customer_signed_in? %>
            <%= current_customer.description %> | 
            <%= link_to 'Meus Pedidos', orders_path %>
            <%= button_to 'Sair', destroy_customer_session_path, method: :delete %>

          <% else %>
            <%= link_to 'Login para Dono de Buffet', new_owner_session_path %> | 
            <%= link_to 'Login para Clientes', new_customer_session_path %>
          <% end %>

        </div>
      </nav>
    </header>
    <main>
      <div>
        <%= notice %>
        <%= alert %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>